src/main/java/com/ohdaesan/shallwepets/auth/config/WebSecurityConfig.java, src/main/java/com/ohdaesan/shallwepets/auth/filter/CustomAuthenticationFilter.java, src/main/java/com/ohdaesan/shallwepets/auth/filter/JwtAuthorizationFilter.java, src/main/java/com/ohdaesan/shallwepets/auth/handler/CustomAuthSuccessHandler.java
=> [FIX] REACT 연동 시 발생한 CORS 오류 해결

src/main/java/com/ohdaesan/shallwepets/member/controller/MemberController.java, src/main/java/com/ohdaesan/shallwepets/member/service/MemberService.java
=> [FEAT] 회원가입 기능 구현

src/main/java/com/ohdaesan/shallwepets/auth/handler/CustomAuthSuccessHandler.java
응답 map에 userInfo 대신 nickname으로 변경하여 전송
=> [FIX] 응답 map에 userInfo 대신 nickname으로 변경하여 전송

build.gradle, src/main/java/com/ohdaesan/shallwepets/verification/MailManager.java, src/main/java/com/ohdaesan/shallwepets/verification/SHA256Util.java, src/main/java/com/ohdaesan/shallwepets/verification/controller/MailController.java
=> [FEAT] Email 전송 프로토콜 추가

src/main/java/com/ohdaesan/shallwepets/auth/config/WebSecurityConfig.java, src/main/java/com/ohdaesan/shallwepets/auth/filter/JwtAuthorizationFilter.java, src/main/java/com/ohdaesan/shallwepets/member/controller/MemberController.java, src/main/java/com/ohdaesan/shallwepets/member/repository/MemberRepository.java, src/main/java/com/ohdaesan/shallwepets/member/service/MemberService.java
=> [FEAT] FindId 기능 추가

src/main/java/com/ohdaesan/shallwepets/auth/config/WebSecurityConfig.java, src/main/java/com/ohdaesan/shallwepets/auth/filter/JwtAuthorizationFilter.java, src/main/java/com/ohdaesan/shallwepets/member/controller/MemberController.java, src/main/java/com/ohdaesan/shallwepets/member/repository/MemberRepository.java, src/main/java/com/ohdaesan/shallwepets/member/service/MemberService.java
=> [FEAT] 비밀번호 찾기 기능 추가

src/main/java/com/ohdaesan/shallwepets/auth/config/WebSecurityConfig.java, src/main/java/com/ohdaesan/shallwepets/auth/filter/JwtAuthorizationFilter.java, src/main/java/com/ohdaesan/shallwepets/member/controller/MemberController.java, src/main/java/com/ohdaesan/shallwepets/member/repository/MemberRepository.java, src/main/java/com/ohdaesan/shallwepets/member/service/MemberService.java
=> [FEAT] 비밀번호 찾기 - 유효한 정보 입력 시 비밀번호 변경

build.gradle, src/main/java/com/ohdaesan/shallwepets/auth/config/WebSecurityConfig.java, src/main/java/com/ohdaesan/shallwepets/auth/filter/JwtAuthorizationFilter.java, src/main/java/com/ohdaesan/shallwepets/csvR/controller/CsvToDbController.java, src/main/java/com/ohdaesan/shallwepets/post/domain/dto/PostDTO.java, src/main/java/com/ohdaesan/shallwepets/post/domain/entity/Post.java
=> [FEAT]csv파일 DB연동

src/main/java/com/ohdaesan/shallwepets/member/controller/MemberController.java
=> [FIX] return 타입 변경

src/main/java/com/ohdaesan/shallwepets/auth/handler/CustomAuthFailUserHandler.java, src/main/java/com/ohdaesan/shallwepets/auth/service/CustomUserDetailService.java, src/main/java/com/ohdaesan/shallwepets/global/UserStatusException.java
=> [FEAT] 로그인 시 회원의 status(정지나 탈퇴 여부) 확인하는 기능 추가

src/main/java/com/ohdaesan/shallwepets/auth/config/WebConfig.java, src/main/java/com/ohdaesan/shallwepets/auth/config/WebSecurityConfig.java, src/main/java/com/ohdaesan/shallwepets/auth/filter/JwtAuthorizationFilter.java, src/main/java/com/ohdaesan/shallwepets/csvR/controller/CsvToDbController.java, src/main/java/com/ohdaesan/shallwepets/post/controller/PostController.java, src/main/java/com/ohdaesan/shallwepets/post/domain/dto/PostDTO.java, src/main/java/com/ohdaesan/shallwepets/post/service/PostService.java
=> [FEAT] api post 연동

src/main/java/com/ohdaesan/shallwepets/auth/config/SwaggerConfig.java
=> [FEAT] Swagger OpenAPI Bean 추가

build.gradle, src/main/java/com/ohdaesan/shallwepets/auth/config/WebSecurityConfig.java, src/main/java/com/ohdaesan/shallwepets/auth/filter/JwtAuthorizationFilter.java, src/main/java/com/ohdaesan/shallwepets/verification/controller/SMSController.java, src/main/java/com/ohdaesan/shallwepets/verification/service/SMSService.java
=> [FEAT] 핸드폰 번호 인증 기능 추가

src/main/java/com/ohdaesan/shallwepets/images/controller/ImagesController.java, src/main/java/com/ohdaesan/shallwepets/images/service/ImagesService.java
=> [FEAT] 이미지 업로드 후 리턴 타입 변경

src/main/java/com/ohdaesan/shallwepets/auth/config/WebSecurityConfig.java, src/main/java/com/ohdaesan/shallwepets/auth/filter/JwtAuthorizationFilter.java, src/main/java/com/ohdaesan/shallwepets/bookmark/controller/BookmarkController.java, src/main/java/com/ohdaesan/shallwepets/bookmark/repository/BookmarkRepository.java, src/main/java/com/ohdaesan/shallwepets/bookmark/service/BookmarkService.java, src/main/java/com/ohdaesan/shallwepets/point/controller/PointController.java, src/main/java/com/ohdaesan/shallwepets/post/controller/PostController.java, src/main/java/com/ohdaesan/shallwepets/post/service/PostService.java, src/main/java/com/ohdaesan/shallwepets/review/controller/ReviewController.java, src/main/java/com/ohdaesan/shallwepets/review/repository/ReviewRepository.java, src/main/java/com/ohdaesan/shallwepets/review/service/ReviewService.java
[FEAT] 북마크 crd 추가,  postNo로 리뷰 별점 평균 및 총 리뷰수 조회
=> [FEAT] 북마크 crd 추가,  postNo로 리뷰 별점 평균 및 총 리뷰수 조회

src/main/java/com/ohdaesan/shallwepets/auth/handler/CustomAuthSuccessHandler.java
=> [FEAT] 로그인 응답 시 멤버 넘버도 같이 담아서 전송

src/main/java/com/ohdaesan/shallwepets/bookmark/controller/BookmarkController.java, src/main/java/com/ohdaesan/shallwepets/bookmark/service/BookmarkService.java
[FEAT]bookMark Api로 back-front연동
=> [FEAT]bookMark Api로 back-front연동 

src/main/java/com/ohdaesan/shallwepets/auth/config/WebSecurityConfig.java, src/main/java/com/ohdaesan/shallwepets/images/controller/ImagesController.java
ImagesController의 parameter 타입 변경
=> [FEAT] ImagesController의 parameter 타입 변경

src/main/java/com/ohdaesan/shallwepets/auth/filter/JwtAuthorizationFilter.java, src/main/java/com/ohdaesan/shallwepets/member/controller/MemberController.java, src/main/java/com/ohdaesan/shallwepets/member/repository/MemberRepository.java, src/main/java/com/ohdaesan/shallwepets/member/service/MemberService.java
=> [FEAT] 멤버 아이디로 닉네임 받아오기

src/main/java/com/ohdaesan/shallwepets/auth/filter/JwtAuthorizationFilter.java, src/main/java/com/ohdaesan/shallwepets/member/controller/MemberController.java, src/main/java/com/ohdaesan/shallwepets/member/service/MemberService.java
=> [FEAT] 멤버 넘버로 회원등급 받아오기

src/main/java/com/ohdaesan/shallwepets/auth/filter/JwtAuthorizationFilter.java, src/main/java/com/ohdaesan/shallwepets/images/controller/ImagesController.java, src/main/java/com/ohdaesan/shallwepets/images/repository/ImagesRepository.java, src/main/java/com/ohdaesan/shallwepets/images/service/ImagesService.java
=> [FEAT] AWS S3 이미지 불러오는 기능

src/main/java/com/ohdaesan/shallwepets/auth/handler/CustomAuthSuccessHandler.java
=> [FEAT] 로그인 응답 시 멤버 등급도 같이 담아서 전송

src/main/java/com/ohdaesan/shallwepets/auth/config/SwaggerConfig.java, src/main/java/com/ohdaesan/shallwepets/auth/filter/JwtAuthorizationFilter.java, src/main/java/com/ohdaesan/shallwepets/auth/handler/CustomAuthSuccessHandler.java, src/main/java/com/ohdaesan/shallwepets/images/controller/ImagesController.java, src/main/java/com/ohdaesan/shallwepets/images/service/ImagesService.java, src/main/java/com/ohdaesan/shallwepets/images/service/S3Service.java
=> [FEAT] AWS S3 이미지 파일 수정 기능

src/main/java/com/ohdaesan/shallwepets/member/controller/MemberController.java
=> [STYLE] Swagger 설명 추가

src/main/java/com/ohdaesan/shallwepets/post/controller/PostController.java, src/main/java/com/ohdaesan/shallwepets/post/repository/PostRepository.java, src/main/java/com/ohdaesan/shallwepets/post/service/PostService.java
카테고리와 도시에 해당하는 장소(post) 목록 DB에서 가져오기
=> [FEAT] 카테고리와 도시에 해당하는 장소(post) 목록 DB에서 가져오기

src/main/java/com/ohdaesan/shallwepets/post/controller/PostController.java, src/main/java/com/ohdaesan/shallwepets/post/repository/PostRepository.java, src/main/java/com/ohdaesan/shallwepets/post/service/PostService.java
사용자가 고른 카테고리와 도시에 해당하는 시군구 리스트 조회
=> [FEAT] 사용자가 고른 카테고리와 도시에 해당하는 시군구 리스트 조회

src/main/java/com/ohdaesan/shallwepets/post/controller/PostController.java, src/main/java/com/ohdaesan/shallwepets/post/repository/PostRepository.java, src/main/java/com/ohdaesan/shallwepets/post/service/PostService.java
도시 이름이 정확하게 일치하지 않더라도 이름을 포함하고 있으면 장소 목록에 포함하도록 수정
=> [FIX] 도시 이름이 정확하게 일치하지 않더라도 이름을 포함하고 있으면 장소 목록에 포함하도록 수정

src/main/java/com/ohdaesan/shallwepets/auth/filter/JwtAuthorizationFilter.java, src/main/java/com/ohdaesan/shallwepets/images/controller/ImagesController.java, src/main/java/com/ohdaesan/shallwepets/member/repository/MemberRepository.java, src/main/java/com/ohdaesan/shallwepets/member/service/MemberService.java, src/main/java/com/ohdaesan/shallwepets/review/controller/ReviewController.java, src/main/java/com/ohdaesan/shallwepets/review/service/ReviewService.java
=> [FEAT] 회원 번호로 이미지 가져오는 기능

src/main/java/com/ohdaesan/shallwepets/auth/config/BeanConfiguration.java
Post를 PostDTO로 매핑 시 enum 타입은 매핑제외되는 오류 수정
=> [FIX] Post를 PostDTO로 매핑 시 enum 타입은 매핑제외되는 오류 수정

src/main/java/com/ohdaesan/shallwepets/post/domain/dto/PostImagesDTO.java, src/main/java/com/ohdaesan/shallwepets/review/domain/dto/ReviewImagesDTO.java
PostImagesDTO와 ReviewImagesDTO에 id 추가
=> [FIX] PostImagesDTO와 ReviewImagesDTO에 id 추가

src/main/java/com/ohdaesan/shallwepets/images/controller/ImagesController.java, src/main/java/com/ohdaesan/shallwepets/post/controller/PostController.java, src/main/java/com/ohdaesan/shallwepets/post/domain/dto/PostDTO.java, src/main/java/com/ohdaesan/shallwepets/post/repository/PostRepository.java, src/main/java/com/ohdaesan/shallwepets/post/service/PostService.java
=> [FEAT] 포스트 목록 무한스크롤 구현

src/main/java/com/ohdaesan/shallwepets/auth/config/S3Config.java, src/main/java/com/ohdaesan/shallwepets/images/domain/dto/ImagesDTO.java, src/main/java/com/ohdaesan/shallwepets/images/domain/entity/Images.java, src/main/java/com/ohdaesan/shallwepets/images/repository/ImagesRepository.java, src/main/java/com/ohdaesan/shallwepets/images/service/S3Service.java, src/main/java/com/ohdaesan/shallwepets/member/service/MyPageService.java, src/main/java/com/ohdaesan/shallwepets/post/repository/PostRepository.java, src/main/java/com/ohdaesan/shallwepets/post/service/PostService.java
=> [FIX] 충돌 시 Overwrite된 파일 복구

src/main/java/com/ohdaesan/shallwepets/images/controller/ImagesController.java, src/main/java/com/ohdaesan/shallwepets/images/repository/ImagesRepository.java, src/main/java/com/ohdaesan/shallwepets/images/service/ImagesService.java
=> [FEAT] 업체가 등록한 이미지 목록 가져오기

src/main/java/com/ohdaesan/shallwepets/auth/filter/JwtAuthorizationFilter.java, src/main/java/com/ohdaesan/shallwepets/images/controller/ImagesController.java, src/main/java/com/ohdaesan/shallwepets/images/repository/ImagesRepository.java, src/main/java/com/ohdaesan/shallwepets/images/service/ImagesService.java
포스트 상세페이지에서 사진을 받아올 때 포스트 번호로 관련 이미지들 페이징 처리하여 가져오는 기능 추가
=> [FEAT] 포스트 상세페이지에서 사진을 받아올 때 포스트 번호로 관련 이미지들 페이징 처리하여 가져오는 기능 추가

src/main/java/com/ohdaesan/shallwepets/review/controller/ReviewController.java
=> [FIX] 리뷰 삭제/수정 path 변경

src/main/java/com/ohdaesan/shallwepets/review/controller/ReviewController.java, src/main/java/com/ohdaesan/shallwepets/review/domain/dto/ReviewUpdateRequestDTO.java, src/main/java/com/ohdaesan/shallwepets/review/domain/entity/Review.java, src/main/java/com/ohdaesan/shallwepets/review/service/ReviewService.java
리뷰 수정 시 요청받아올 request DTO 추가, 리뷰 수정 시 이미지 수정 기능 추가
=> [FEAT] 리뷰 수정 시 요청받아올 request DTO 추가, 리뷰 수정 시 이미지 수정 기능 추가

src/main/java/com/ohdaesan/shallwepets/member/controller/MemberController.java, src/main/java/com/ohdaesan/shallwepets/post/controller/PostController.java, src/main/java/com/ohdaesan/shallwepets/post/domain/entity/Post.java, src/main/java/com/ohdaesan/shallwepets/post/repository/PostRepository.java, src/main/java/com/ohdaesan/shallwepets/post/service/PostService.java
=> [FEAT] 관리자 업체 승인 기능

src/main/java/com/ohdaesan/shallwepets/auth/filter/JwtAuthorizationFilter.java, src/main/java/com/ohdaesan/shallwepets/images/controller/ImagesController.java
포스트 번호로 업체가 직접 등록한 이미지들 가져오는 메소드를 로그인 안해도 허용
=> [FIX] 포스트 번호로 업체가 직접 등록한 이미지들 가져오는 메소드를 로그인 안해도 허용

src/main/java/com/ohdaesan/shallwepets/auth/handler/CustomAuthSuccessHandler.java, src/main/java/com/ohdaesan/shallwepets/post/controller/PostController.java, src/main/java/com/ohdaesan/shallwepets/post/repository/PostRepository.java, src/main/java/com/ohdaesan/shallwepets/post/service/PostService.java
ADMIN으로 로그인 시 구분할 회원 status 보내기, 모든 업체 조회 메소드 추가
=> [FEAT] ADMIN으로 로그인 시 구분할 회원 status 보내기, 모든 업체 조회 메소드 추가

src/main/java/com/ohdaesan/shallwepets/member/service/MyPageService.java
=> [FIX] 우편번호 주소 조회+수정 빠졌던 것 수정
